#ifndef __CMDPROC_H
#define __CMDPROC_H

#ifdef __cplusplus
extern "C" {
#endif

#include "hi_type.h"



typedef enum E_MSC_DV_CMD_PARAM 
{
	//WORK STATUS
	WORK_START = 1,
	WORK_STOP,

	//COMMON PARAM
	PHOTO_TIME_INTERVAL_0x1S,
	PHOTO_TIME_INTERVAL_0x5S,
	PHOTO_TIME_INTERVAL_1S,
	PHOTO_EXPOSURE_MODE_AUTO,
	PHOTO_EXPOSURE_MODE_MANUAL,
	
	KEY_IDX_POWER_SHORT_DOWN,
	KEY_IDX_POWER_LONG_DOWN,

} MSC_DV_CMD_PARAM;


typedef enum E_MSC_DV_CMD 
{


	//Hardware
	CMD_SET_LED = 1,
	CMD_SET_SD_STATE,
	CMD_SET_WIFI_STATE,
	CMD_SET_BLUETOOTH_STATE,
	CMD_SET_LIGHT_MODULE_STATE,
	CMD_SHUT_DOWN,
	CMD_REBOOT,

	MAX_MSC_CMD_SET_HARDWARE,


	

//SNAP
	CMS_SNAP_CMD_START,
	
	//System Param
	CMD_SET_PARAM_SYS_TIME,

	MAX_MSC_CMD_SET_SYS_PARAM,

	//Snap Param
	CMD_SET_PARAM_ENABLE_SENSOR,
	CMD_SET_PARAM_SNAP_MODE,
	CMD_SET_PARAM_SNAP_TIME_INTERVAL,
	CMD_SET_PARAM_SNAP_DISTANCE,
	CMD_SET_PARAM_EXPOSURE_MODE,
	CMD_SET_PARAM_EXPOSURE_ATTR,

	MAX_MSC_CMD_SET_SNAP_PARAM,
	CMS_START_SNAP_CALIBRATION,
	CMS_START_SNAP_CALIBRATION_TEST,
	CMS_START_SNAP_TASK_ALL,
	CMS_START_SNAP_TASK_ALL_TEST,
	CMS_STOP_SNAP_TASK_ALL,	
	CMS_STOP_SNAP_TASK_ALL_TEST,
	CMS_SNAP_ONCE_ALL,
	CMS_SNAP_ONCE_ALL_TEST,//25

	CMD_GET_Y_FRAME,

	CMS_START_TEST_ISO_BRIGHTNESS_TEST,
	CMD_GET_PARAM_SNAP_MODE,
	CMD_GET_PARAM_SNAP_TIME_INTERVAL,
	CMD_GET_PARAM_SNAP_DISTANCE,
	CMD_GET_PARAM_EXPOSURE_MODE,
	CMD_GET_PARAM_EXPOSURE_ATTR,
	
	CMS_SNAP_CMD_MAX,


	//=====FILE======

	CMD_FILE_CMD_START,


	CMD_GET_GROUP_NUMBER,
	CMD_GET_WORK_NUMBER,
	CMD_GET_FILE_NUMBER,
	CMD_GET_FILE_NUMBER_CAMID,

	CMD_FILE_CMD_MAX,


	//========Hardware==========
	CMD_HARDWARE_START,
	
	CMD_GET_SD_STATE,
	CMD_FORMAT_SD,	
	CMD_GET_GPS_STATE,
	CMD_GET_WIFI_STATE,
	CMD_GET_BLUETOOTH_STATE,
	CMD_GET_LIGHT_MODULE_STATE,
	
	MAX_MSC_CMD_GET_HARDWARE,

	CMD_HARDWARE_MAX,
	

	//System Param
	CMD_GET_PARAM_SYS_VERSION,
	CMD_GET_PARAM_SYS_TIME,

	MAX_MSC_CMD_GET_SYS_PARAM,

	//Snap Param





	MAX_MSC_CMD_GET_SNAP_PARAM,



	/***************Event****************/
	CMD_KEY_STATE_CHANGE,


	
	
} MSC_DV_CMD;

typedef struct
{
	HI_U32 GroupIndex;
	HI_U32 WorkIndex;
	HI_U32 CamID;
} GROUP_WORK_S;
typedef HI_S32 (*pfCallBack)(MSC_DV_CMD cmdID, HI_S32 cmdParam, HI_VOID *setVal, HI_VOID *retVal);

HI_S32 CmdProcInit(pfCallBack pCallBack);


#ifdef __cplusplus
}
#endif

#endif 

